'use strict';

var PMConstants = {
  DOMAIN : "*",
  RECIPIENT : {
    SERVER : "SERVER",
    ALL : "*"
  },
  IFRAME_PREFIX : "PMIFRAME_%ID%",
  REQUEST : {
    GET_CONNECT_CLIENT : "GET/CONNECT-CLIENT",
    GET_DISCONNECT_CLIENT : "GET/DISCONNECT-CLIENT",
    GET_CLIENTS : "GET/GET-CLIENTS",
    POST_MESSAGE_CLIENT: "POST/SEND-MESSAGE-CLIENT",
    POST_MESSAGE_CLIENTS: "POST/SEND-MESSAGE-CLIENTS"
  }
};